version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: prettier
    versions:
    - ">= 2.a, < 3"
  - dependency-name: aws-sdk
    versions:
    - ">= 2, < 3"
